kind: Pod
apiVersion: v1
metadata:
  name: busybox-secrets-store
spec:
  serviceAccountName: "workload-identity-sa"
  containers:
    - name: busybox
      image: k8s.gcr.io/e2e-test-images/busybox:1.29-1
      command:
        - "/bin/sleep"
        - "10000"
      volumeMounts:
      - name: tls-secret-store
        mountPath: "/mnt/secrets-store"
        readOnly: true
      env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: aks-ingress-tls
            key: tls.key
  volumes:
    - name: tls-secret-store
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-sprovider-wi"
