apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-workload-identity # needs to be unique per namespace
spec:
  provider: azure
  secretObjects:                                        # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: aks-ingress-tls                         # name of the K8s Secret object
    type: kubernetes.io/tls                             # type of the K8s Secret object e.g. Opaque, kubernetes.io/tls
    data: 
    - objectName: aks-ingress-tls-crt                   # name of the mounted content to sync with K8s Secret object
      key: tls.key
    - objectName: aks-ingress-tls-crt
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    clientID: <USER_ASSIGNED_CLIENT_ID>  #"ecd35607-b43d-4cae-9b4c-d3d3a210e83f" # Setting this to use workload identity
    keyvaultName: <KEYVAULT_NAME>        # "akskeyvault112" Set to the name of your key vault
    cloudName: ""                        # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: <KEYVAULT_CERT_NAME>             #"aksingresstls"
          objectType: cert           # object types: secret, key, or cert
          objectVersion: ""          # [OPTIONAL] object versions, default to latest if empty
    tenantId: <AZURE_TENANT_ID>      #"36fc4188-834c-442f-b83d-f898cbd0df86"The tenant ID of the key vault
